<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<!-- git web interface version 1.7.3.GIT, (C) 2005-2006, Kay Sievers <kay.sievers@vrfy.org>, Christian Gierke -->
<!-- git core binaries version 1.7.4.1 -->
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
<meta name="generator" content="gitweb/1.7.3.GIT git/1.7.4.1"/>
<meta name="robots" content="index, nofollow"/>
<title>drupalcode.org Git - sandbox/iqbalnurhakim/1623992.git/blob - vegas.install</title>
<base href="http://drupalcode.org" />
<link rel="stylesheet" type="text/css" href="/gitweb.css"/>
<link rel="stylesheet" type="text/css" href="/highlight.css"/>
<link rel="alternate" title="sandbox/iqbalnurhakim/1623992.git - history of vegas.install on '7.x-1.x' - RSS feed" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/rss/refs/heads/7.x-1.x?f=vegas.install" type="application/rss+xml" />
<link rel="alternate" title="sandbox/iqbalnurhakim/1623992.git - history of vegas.install on '7.x-1.x' - RSS feed (no merges)" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/rss/refs/heads/7.x-1.x?f=vegas.install;opt=--no-merges" type="application/rss+xml" />
<link rel="alternate" title="sandbox/iqbalnurhakim/1623992.git - history of vegas.install on '7.x-1.x' - Atom feed" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/atom/refs/heads/7.x-1.x?f=vegas.install;opt=--no-merges" type="application/atom+xml" />
<link rel="alternate" title="sandbox/iqbalnurhakim/1623992.git - history of vegas.install on '7.x-1.x' - Atom feed (no merges)" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/atom/refs/heads/7.x-1.x?f=vegas.install;opt=--no-merges" type="application/atom+xml" />
<link rel="shortcut icon" href="/git-favicon.png" type="image/png" />
</head>
<body>
<div class="page_header">
<a title="git homepage" href="http://drupal.org/"><img src="/git-logo.png" width="72" height="27" alt="git" class="logo"/></a><a href="/">projects</a> / <a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git">sandbox/iqbalnurhakim/1623992.git</a> / blob
</div>
<form method="get" action="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git" enctype="application/x-www-form-urlencoded">
<div class="search">
<input name="a" type="hidden" value="search" />
<input name="h" type="hidden" value="refs/heads/7.x-1.x" />
<select name="st" >
<option selected="selected" value="commit">commit</option>
<option value="grep">grep</option>
<option value="author">author</option>
<option value="committer">committer</option>
<option value="pickaxe">pickaxe</option>
</select><sup><a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/search_help">?</a></sup> search:
<input type="text" name="s"  />
<span title="Extended regular expression"><label><input type="checkbox" name="sr" value="1" />re</label></span></div>
</form>
<div class="page_nav">
<a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git">summary</a> | <a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/shortlog">shortlog</a> | <a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/log">log</a> | <a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/commit/refs/heads/7.x-1.x">commit</a> | <a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/commitdiff/refs/heads/7.x-1.x">commitdiff</a> | <a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/tree/refs/heads/7.x-1.x">tree</a><br/>
<a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blame/refs/heads/7.x-1.x:/vegas.install">blame</a> | <a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/history/refs/heads/7.x-1.x:/vegas.install">history</a> | <a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob_plain/refs/heads/7.x-1.x:/vegas.install">raw</a> | <a href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/HEAD:/vegas.install">HEAD</a><br/>
</div>
<div class="header">
<a class="title" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/commit/refs/heads/7.x-1.x">Fixed drupal standard codes</a>
</div>
<div class="page_path"><a title="tree root" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/tree/refs/heads/7.x-1.x">[sandbox/iqbalnurhakim/1623992.git]</a> / <a title="vegas.install" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob_plain/refs/heads/7.x-1.x:/vegas.install">vegas.install</a><br/></div>
<div class="page_body">
<div class="pre"><a id="l1" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l1" class="linenr">   1</a> <span class="hl sym">&lt;</span>?php</div>
<div class="pre"><a id="l2" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l2" class="linenr">   2</a> <span class="hl com">/**</span></div>
<div class="pre"><a id="l3" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l3" class="linenr">   3</a> <span class="hl com"> * &#64;file</span></div>
<div class="pre"><a id="l4" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l4" class="linenr">   4</a> <span class="hl com"> * Installation requirement and schema difinition of module vegas</span></div>
<div class="pre"><a id="l5" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l5" class="linenr">   5</a> <span class="hl com"> */</span></div>
<div class="pre"><a id="l6" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l6" class="linenr">   6</a> </div>
<div class="pre"><a id="l7" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l7" class="linenr">   7</a> <span class="hl com">/**</span></div>
<div class="pre"><a id="l8" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l8" class="linenr">   8</a> <span class="hl com"> * Implements hook_requirements().</span></div>
<div class="pre"><a id="l9" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l9" class="linenr">   9</a> <span class="hl com"> */</span></div>
<div class="pre"><a id="l10" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l10" class="linenr">  10</a> <span class="hl kwa">function</span> <span class="hl kwd">vegas_requirements</span><span class="hl sym">(</span><span class="hl kwc">$phase</span><span class="hl sym">) {</span></div>
<div class="pre"><a id="l11" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l11" class="linenr">  11</a>   <span class="hl kwc">$t</span> <span class="hl sym">=</span> <span class="hl kwd">get_t</span><span class="hl sym">();</span></div>
<div class="pre"><a id="l12" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l12" class="linenr">  12</a>   <span class="hl kwc">$requirements</span> <span class="hl sym">=</span> <span class="hl kwa">array</span><span class="hl sym">();</span></div>
<div class="pre"><a id="l13" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l13" class="linenr">  13</a>   <span class="hl kwa">if</span> <span class="hl sym">(</span><span class="hl kwc">$phase</span> <span class="hl sym">==</span> <span class="hl str">'runtime'</span><span class="hl sym">) {</span></div>
<div class="pre"><a id="l14" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l14" class="linenr">  14</a>     <span class="hl kwa">if</span> <span class="hl sym">(</span><span class="hl kwd">vegas_get_path</span><span class="hl sym">() ==</span> NULL<span class="hl sym">) {</span></div>
<div class="pre"><a id="l15" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l15" class="linenr">  15</a>       <span class="hl kwc">$requirements</span><span class="hl sym">[</span><span class="hl str">'vegas'</span><span class="hl sym">] =</span> <span class="hl kwa">array</span><span class="hl sym">(</span></div>
<div class="pre"><a id="l16" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l16" class="linenr">  16</a>         <span class="hl str">'title'</span> <span class="hl sym">=&gt;</span> <span class="hl kwc">$t</span><span class="hl sym">(</span><span class="hl str">'Vegas'</span><span class="hl sym">),</span></div>
<div class="pre"><a id="l17" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l17" class="linenr">  17</a>         <span class="hl str">'value'</span> <span class="hl sym">=&gt;</span> <span class="hl kwc">$t</span><span class="hl sym">(</span><span class="hl str">'Jquery Vegas library is not configured'</span><span class="hl sym">),</span></div>
<div class="pre"><a id="l18" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l18" class="linenr">  18</a>         <span class="hl str">'severity'</span> <span class="hl sym">=&gt;</span> REQUIREMENT_ERROR<span class="hl sym">,</span></div>
<div class="pre"><a id="l19" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l19" class="linenr">  19</a>         <span class="hl str">'description'</span> <span class="hl sym">=&gt;</span> <span class="hl kwc">$t</span><span class="hl sym">(</span><span class="hl str">'You need to download the !vegas and extract the entire contents of the archive into the %path folder of your server.'</span><span class="hl sym">,</span></div>
<div class="pre"><a id="l20" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l20" class="linenr">  20</a>           <span class="hl kwa">array</span><span class="hl sym">(</span></div>
<div class="pre"><a id="l21" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l21" class="linenr">  21</a>             <span class="hl str">'!vegas'</span> <span class="hl sym">=&gt;</span> <span class="hl kwd">l</span><span class="hl sym">(</span><span class="hl kwc">$t</span><span class="hl sym">(</span><span class="hl str">'JQuery Vegas'</span><span class="hl sym">),</span> <span class="hl str">'http://vegas.jaysalvat.com/'</span><span class="hl sym">),</span></div>
<div class="pre"><a id="l22" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l22" class="linenr">  22</a>             <span class="hl str">'%path'</span> <span class="hl sym">=&gt;</span> VEGAS_PATH<span class="hl sym">,</span></div>
<div class="pre"><a id="l23" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l23" class="linenr">  23</a>           <span class="hl sym">)</span></div>
<div class="pre"><a id="l24" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l24" class="linenr">  24</a>         <span class="hl sym">),</span></div>
<div class="pre"><a id="l25" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l25" class="linenr">  25</a>       <span class="hl sym">);</span></div>
<div class="pre"><a id="l26" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l26" class="linenr">  26</a>     <span class="hl sym">}</span></div>
<div class="pre"><a id="l27" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l27" class="linenr">  27</a>     <span class="hl kwa">else</span> <span class="hl sym">{</span></div>
<div class="pre"><a id="l28" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l28" class="linenr">  28</a>       <span class="hl kwc">$requirements</span><span class="hl sym">[</span><span class="hl str">'vegas'</span><span class="hl sym">] =</span> <span class="hl kwa">array</span><span class="hl sym">(</span></div>
<div class="pre"><a id="l29" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l29" class="linenr">  29</a>         <span class="hl str">'title'</span> <span class="hl sym">=&gt;</span> <span class="hl kwc">$t</span><span class="hl sym">(</span><span class="hl str">'Vegas'</span><span class="hl sym">),</span></div>
<div class="pre"><a id="l30" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l30" class="linenr">  30</a>         <span class="hl str">'value'</span> <span class="hl sym">=&gt;</span> <span class="hl kwc">$t</span><span class="hl sym">(</span><span class="hl str">'Jquery Vegas library already configured properly'</span><span class="hl sym">),</span></div>
<div class="pre"><a id="l31" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l31" class="linenr">  31</a>         <span class="hl str">'severity'</span> <span class="hl sym">=&gt;</span> REQUIREMENT_OK<span class="hl sym">,</span></div>
<div class="pre"><a id="l32" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l32" class="linenr">  32</a>       <span class="hl sym">);</span></div>
<div class="pre"><a id="l33" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l33" class="linenr">  33</a>     <span class="hl sym">}</span></div>
<div class="pre"><a id="l34" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l34" class="linenr">  34</a>   <span class="hl sym">}</span></div>
<div class="pre"><a id="l35" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l35" class="linenr">  35</a>   <span class="hl kwa">return</span> <span class="hl kwc">$requirements</span><span class="hl sym">;</span></div>
<div class="pre"><a id="l36" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l36" class="linenr">  36</a> <span class="hl sym">}</span></div>
<div class="pre"><a id="l37" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l37" class="linenr">  37</a> </div>
<div class="pre"><a id="l38" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l38" class="linenr">  38</a> <span class="hl com">/**</span></div>
<div class="pre"><a id="l39" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l39" class="linenr">  39</a> <span class="hl com"> * Implements hook_schema().</span></div>
<div class="pre"><a id="l40" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l40" class="linenr">  40</a> <span class="hl com"> */</span></div>
<div class="pre"><a id="l41" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l41" class="linenr">  41</a> <span class="hl kwa">function</span> <span class="hl kwd">vegas_schema</span><span class="hl sym">() {</span></div>
<div class="pre"><a id="l42" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l42" class="linenr">  42</a>   <span class="hl kwc">$schema</span><span class="hl sym">[</span><span class="hl str">'vegas_images'</span><span class="hl sym">] =</span> <span class="hl kwa">array</span><span class="hl sym">(</span></div>
<div class="pre"><a id="l43" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l43" class="linenr">  43</a>     <span class="hl str">'description'</span> <span class="hl sym">=&gt;</span> <span class="hl str">'Store vegas image and order configuration.'</span><span class="hl sym">,</span></div>
<div class="pre"><a id="l44" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l44" class="linenr">  44</a>     <span class="hl str">'fields'</span> <span class="hl sym">=&gt;</span> <span class="hl kwa">array</span><span class="hl sym">(</span></div>
<div class="pre"><a id="l45" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l45" class="linenr">  45</a>       <span class="hl str">'fid'</span> <span class="hl sym">=&gt;</span> <span class="hl kwa">array</span><span class="hl sym">(</span></div>
<div class="pre"><a id="l46" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l46" class="linenr">  46</a>         <span class="hl str">'description'</span> <span class="hl sym">=&gt;</span> <span class="hl str">'Vegas images fid.'</span><span class="hl sym">,</span></div>
<div class="pre"><a id="l47" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l47" class="linenr">  47</a>         <span class="hl str">'type'</span> <span class="hl sym">=&gt;</span> <span class="hl str">'serial'</span><span class="hl sym">,</span></div>
<div class="pre"><a id="l48" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l48" class="linenr">  48</a>         <span class="hl str">'unsigned'</span> <span class="hl sym">=&gt;</span> TRUE<span class="hl sym">,</span></div>
<div class="pre"><a id="l49" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l49" class="linenr">  49</a>         <span class="hl str">'not null'</span> <span class="hl sym">=&gt;</span> TRUE<span class="hl sym">,</span></div>
<div class="pre"><a id="l50" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l50" class="linenr">  50</a>       <span class="hl sym">),</span></div>
<div class="pre"><a id="l51" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l51" class="linenr">  51</a>       <span class="hl str">'weight'</span> <span class="hl sym">=&gt;</span> <span class="hl kwa">array</span><span class="hl sym">(</span></div>
<div class="pre"><a id="l52" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l52" class="linenr">  52</a>         <span class="hl str">'description'</span> <span class="hl sym">=&gt;</span> <span class="hl str">'image weight.'</span><span class="hl sym">,</span></div>
<div class="pre"><a id="l53" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l53" class="linenr">  53</a>         <span class="hl str">'type'</span> <span class="hl sym">=&gt;</span> <span class="hl str">'int'</span><span class="hl sym">,</span></div>
<div class="pre"><a id="l54" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l54" class="linenr">  54</a>         <span class="hl str">'unsigned'</span> <span class="hl sym">=&gt;</span> TRUE<span class="hl sym">,</span></div>
<div class="pre"><a id="l55" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l55" class="linenr">  55</a>         <span class="hl str">'not null'</span> <span class="hl sym">=&gt;</span> TRUE<span class="hl sym">,</span></div>
<div class="pre"><a id="l56" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l56" class="linenr">  56</a>         <span class="hl str">'default'</span> <span class="hl sym">=&gt;</span> <span class="hl num">0</span><span class="hl sym">,</span></div>
<div class="pre"><a id="l57" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l57" class="linenr">  57</a>       <span class="hl sym">),</span></div>
<div class="pre"><a id="l58" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l58" class="linenr">  58</a>     <span class="hl sym">),</span></div>
<div class="pre"><a id="l59" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l59" class="linenr">  59</a>     <span class="hl str">'indexes'</span> <span class="hl sym">=&gt;</span> <span class="hl kwa">array</span><span class="hl sym">(</span></div>
<div class="pre"><a id="l60" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l60" class="linenr">  60</a>       <span class="hl str">'vegas_fid'</span> <span class="hl sym">=&gt;</span> <span class="hl kwa">array</span><span class="hl sym">(</span><span class="hl str">'fid'</span><span class="hl sym">),</span></div>
<div class="pre"><a id="l61" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l61" class="linenr">  61</a>       <span class="hl str">'weight'</span> <span class="hl sym">=&gt;</span> <span class="hl kwa">array</span><span class="hl sym">(</span><span class="hl str">'weight'</span><span class="hl sym">),</span></div>
<div class="pre"><a id="l62" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l62" class="linenr">  62</a>     <span class="hl sym">),</span></div>
<div class="pre"><a id="l63" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l63" class="linenr">  63</a>     <span class="hl str">'primary key'</span> <span class="hl sym">=&gt;</span> <span class="hl kwa">array</span><span class="hl sym">(</span><span class="hl str">'fid'</span><span class="hl sym">),</span></div>
<div class="pre"><a id="l64" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l64" class="linenr">  64</a>   <span class="hl sym">);</span></div>
<div class="pre"><a id="l65" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l65" class="linenr">  65</a>   <span class="hl kwa">return</span> <span class="hl kwc">$schema</span><span class="hl sym">;</span></div>
<div class="pre"><a id="l66" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l66" class="linenr">  66</a> <span class="hl sym">}</span></div>
<div class="pre"><a id="l67" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l67" class="linenr">  67</a> </div>
<div class="pre"><a id="l68" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l68" class="linenr">  68</a> <span class="hl com">/**</span></div>
<div class="pre"><a id="l69" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l69" class="linenr">  69</a> <span class="hl com"> * Implements hook_uninstall().</span></div>
<div class="pre"><a id="l70" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l70" class="linenr">  70</a> <span class="hl com"> */</span></div>
<div class="pre"><a id="l71" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l71" class="linenr">  71</a> <span class="hl kwa">function</span> <span class="hl kwd">vegas_uninstall</span><span class="hl sym">() {</span></div>
<div class="pre"><a id="l72" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l72" class="linenr">  72</a>   <span class="hl kwd">variable_del</span><span class="hl sym">(</span><span class="hl str">'vegas_library_path'</span><span class="hl sym">);</span></div>
<div class="pre"><a id="l73" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l73" class="linenr">  73</a>   <span class="hl kwd">variable_del</span><span class="hl sym">(</span><span class="hl str">'vegas_use_overlay'</span><span class="hl sym">);</span></div>
<div class="pre"><a id="l74" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l74" class="linenr">  74</a>   <span class="hl kwd">variable_del</span><span class="hl sym">(</span><span class="hl str">'vegas_overlay_textures'</span><span class="hl sym">);</span></div>
<div class="pre"><a id="l75" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l75" class="linenr">  75</a>   <span class="hl kwd">variable_del</span><span class="hl sym">(</span><span class="hl str">'vegas_use_slideshow'</span><span class="hl sym">);</span></div>
<div class="pre"><a id="l76" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l76" class="linenr">  76</a>   <span class="hl kwd">variable_del</span><span class="hl sym">(</span><span class="hl str">'vegas_slideshow_effect_delay'</span><span class="hl sym">);</span></div>
<div class="pre"><a id="l77" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l77" class="linenr">  77</a>   <span class="hl kwd">variable_del</span><span class="hl sym">(</span><span class="hl str">'vegas_slideshow_effect_step'</span><span class="hl sym">);</span></div>
<div class="pre"><a id="l78" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l78" class="linenr">  78</a>   <span class="hl kwd">variable_del</span><span class="hl sym">(</span><span class="hl str">'vegas_slideshow_effect_preload'</span><span class="hl sym">);</span></div>
<div class="pre"><a id="l79" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install#l79" class="linenr">  79</a> <span class="hl sym">}</span></div>
</div><div class="page_footer">
<div class="cachetime">Cache Last Updated: Sat Jul 14 18:38:56 2012 GMT</div>
<!--
	Full URL: |/sandbox/iqbalnurhakim/1623992.git/blob/refs/heads/7.x-1.x:/vegas.install?|
	URL Hash: |6da3a1729ba9727c9851268c93eb1b4b|
-->
<div class="page_footer_text">For more information about this repository, visit the project page at http://drupal.org/sandbox/iqbalnurhakim/1623992</div>
<a class="rss_logo" title="history of vegas.install on '7.x-1.x' RSS feed" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/rss/refs/heads/7.x-1.x?f=vegas.install">RSS</a>
<a class="rss_logo" title="history of vegas.install on '7.x-1.x' Atom feed" href="http://drupalcode.org/sandbox/iqbalnurhakim/1623992.git/atom/refs/heads/7.x-1.x?f=vegas.install">Atom</a>
</div>
<script type="text/javascript" src="/gitweb.js"></script>
</body>
</html>